on: [push, pull_request]
name: Cabal multi-version build
jobs:
  build-ghc:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.2', '9.4.5', '9.6.2']
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal v1-install --only-dependencies --enable-tests --enable-benchmarks
      - run: cabal v1-configure --enable-tests --enable-benchmarks
      - run: cabal v1-build
      - run: cabal v1-test
      - run: cabal v1-bench
